const db = require('../database/db');
const fs = require('fs');
const path = require('path');
// 1. GET ALL CATEGORIES
const getall = (req, res) => {
    const sql = "SELECT * FROM products";
    db.query(sql, (err, data) => {
        if (err) {
            return res.status(500).json({
                status: false,
                message: err.message
            });
        }
        if (data.length > 0) {
            res.status(200).json({
                status: true,
                message: "Get data successfully!",
                data: data
            });
        } else {
            res.status(404).json({ status: false, message: "Data Not Found!" });
        }
    });
};
// 2. CREATE CATEGORY (With Image Upload)
const create = (req, res) => {
    const { category_id, title, price, description } = req.body;

    // Use the filename generated by Multer (req.file)
    const image = req.file ? req.file.filename : null;

    const sql = `
    INSERT INTO products 
    (category_id ,title ,image ,price ,description )
    VALUES (?, ?, ?, ?, ? )
  `;
    const values = [category_id, title, image, price, description];

    db.query(sql, values, (err, result) => {
        if (err) {
            console.error(err);
            return res.status(500).json({ status: false, message: 'Database error' });
        }
        res.status(201).json({
            status: true,
            message: 'Category created successfully',
            id: result.insertId
        });
    });
};
// 3. REMOVE CATEGORY
const remove = (req, res) => {
  const { id } = req.params;

  // 1. get product first
  const getSql = "SELECT image FROM products WHERE id = ?";
  db.query(getSql, [id], (err, rows) => {
    if (err) return res.status(500).json({ status: false, message: err.message });
    if (rows.length === 0) {
      return res.status(404).json({ status: false, message: "Product not found" });
    }

    const image = rows[0].image;

    // 2. delete image file
    if (image) {
      const imagePath = path.join(__dirname, '../uploads/images', image);
      if (fs.existsSync(imagePath)) {
        fs.unlinkSync(imagePath);
      }
    }

    // 3. delete product
    const deleteSql = "DELETE FROM products WHERE id = ?";
    db.query(deleteSql, [id], (err) => {
      if (err) return res.status(500).json({ status: false, message: err.message });

      res.json({
        status: true,
        message: "Product and image deleted successfully"
      });
    });
  });
};
// 4. EDIT CATEGORY
const edit = (req, res) => {
  const { id } = req.params;

  // 1. get old product
  db.query("SELECT * FROM products WHERE id = ?", [id], (err, rows) => {
    if (err) return res.status(500).json({ status: false, message: err.message });
    if (rows.length === 0) {
      return res.status(404).json({ status: false, message: "Product not found" });
    }

    const old = rows[0];

    // 2. merge new + old
    const category_id = req.body.category_id ?? old.category_id;
    const title = req.body.title ?? old.title;
    const price = req.body.price ?? old.price;
    const description = req.body.description ?? old.description;

    const image = req.file ? req.file.filename : old.image;

    // 3. update
    const sql = `
      UPDATE products
      SET category_id=?, title=?, image=?, price=?, description=?
      WHERE id=?
    `;

    const values = [category_id, title, image, price, description, id];

    db.query(sql, values, (err) => {
      if (err) return res.status(500).json({ status: false, message: err.message });
      res.json({ status: true, message: "Product updated successfully" });
    });
  });
};
// search
const searchData = (req, res) => {
    const { q } = req.query; // get search keyword from URL: /search?q=laptop

    if (!q) {
        return res.status(400).json({ status: false, message: "Please provide a search query" });
    }

    const sql = `
    SELECT * FROM products
    WHERE title LIKE ? 
  `;

    const searchTerm = `%${q}%`; // Add % for SQL LIKE
    db.query(sql, [searchTerm], (err, results) => {
        if (err) {
            console.error(err);
            return res.status(500).json({ status: false, message: "Database error" });
        }

        if (results.length === 0) {
            return res.status(404).json({ status: false, message: "No matching categories found" });
        }

        res.json({ status: true, message: "Search results", data: results });
    });
}
module.exports = {
    getall,
    create,
    remove,
    edit,
    searchData
};